/**
 * Generates a GitHub Actions workflow YAML for automated Confluence publishing.
 *
 * The workflow triggers on push to main for files matching the include pattern,
 * and runs a Python script (or the plugin's CLI) to publish to Confluence.
 */

export class GithubActionsGen {
  /**
   * Generate the GitHub Actions workflow YAML.
   */
  generate(spaceKey: string, parentPageId: string): string {
    return `# Generated by Confluence Git Sync plugin
# This workflow automatically publishes changes to Confluence

name: Publish to Confluence

on:
  push:
    branches:
      - main
    paths:
      - 'prds/B-*.md'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install atlassian-python-api pydantic pydantic-settings python-frontmatter Markdown

      - name: Publish to Confluence
        env:
          CONFLUENCE_BASE_URL: \${{ secrets.CONFLUENCE_BASE_URL }}
          CONFLUENCE_EMAIL: \${{ secrets.CONFLUENCE_EMAIL }}
          CONFLUENCE_API_TOKEN: \${{ secrets.CONFLUENCE_API_TOKEN }}
          CONFLUENCE_SPACE_KEY: ${spaceKey}
          CONFLUENCE_PARENT_PAGE_ID: ${parentPageId}
        run: |
          python scripts/publish_to_confluence.py

      - name: Notify on failure
        if: failure()
        run: |
          echo "Confluence publishing failed. Check the logs above for details."
`;
  }
}
